# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadExcelData.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadExcelBefore_button = QtWidgets.QPushButton(self.centralwidget)
        self.loadExcelBefore_button.setGeometry(QtCore.QRect(20, 30, 381, 34))
        self.loadExcelBefore_button.setObjectName("loadExcelBefore_button")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(50, 270, 361, 261))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(420, 270, 361, 261))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 230, 341, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 230, 351, 20))
        self.label_2.setObjectName("label_2")
        self.loadExcelAfter_button = QtWidgets.QPushButton(self.centralwidget)
        self.loadExcelAfter_button.setGeometry(QtCore.QRect(20, 80, 381, 34))
        self.loadExcelAfter_button.setObjectName("loadExcelAfter_button")
        self.maskEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.maskEdit.setGeometry(QtCore.QRect(600, 40, 113, 26))
        self.maskEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.maskEdit.setObjectName("maskEdit")
        self.RMS_button = QtWidgets.QPushButton(self.centralwidget)
        self.RMS_button.setGeometry(QtCore.QRect(590, 80, 141, 34))
        self.RMS_button.setObjectName("RMS_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadExcelBefore_button.setText(_translate("MainWindow", "Load Excel Before Data"))
        self.label.setText(_translate("MainWindow", "\'Single-Sided Amplitude Spectrum of X(t)\'"))
        self.label_2.setText(_translate("MainWindow", "\'Median Frequecy Amplitude Spectrum of X(t)\'"))
        self.loadExcelAfter_button.setText(_translate("MainWindow", "Load Excel After Data"))
        self.maskEdit.setText(_translate("MainWindow", "50"))
        self.RMS_button.setText(_translate("MainWindow", "RMS Calculate"))
